### ISSUE TITLE
Python macOS issue (ImportError: dlopen(...): no suitable image found. Did find: ...: mach-o, but wrong architecture) 

### ISSUE THREAD

**Issue by thinking-tower** [KomputeProject/kompute#223]
## Issue description

After installing `kp`, `import kp` throws an error.

## Code example

```bash
# use pip
pip install kp 
# or compile from source
git clone https://github.com/EthicalML/vulkan-kompute.git
git submodule update --init --recursive
python setup.py build
python setup.py install
```

```python
>>> import kp
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: dlopen(.../lib/python3.9/site-packages/kp-0.7.0-py3.9-macosx-11-arm64.egg/kp.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        .../lib/python3.9/site-packages/kp-0.7.0-py3.9-macosx-11-arm64.egg/kp.cpython-39-darwin.so: mach-o, but wrong architecture
        .../python3.9/site-packages/kp-0.7.0-py3.9-macosx-11-arm64.egg/kp.cpython-39-darwin.so: mach-o, but wrong architecture

```

## System Info
- OS: macOS Big Sur 11.2.3
- Architecture: arm64
- CMake version: 3.19.6
- Python version: 3.9

**Comment by thinking-tower** [comment]
This can be caused by 
- linking to an Intel-based Python library 
    - Python3.9 ARM and Python3.8 Intel installed in the same machine
- compiling in an Intel-based terminal like Visual Studio Code with Rosetta emulation
    - `uname -m` in emulated Visual Studio Code returns `x86_64` for example.

Here's a couple of solutions:
- Make sure to link to the correct Python library 
- Launch terminal yourself and compile there 
- If you want to compile with an Intel program (Visual Studio Code with Rosetta), pass `-DCMAKE_OSX_ARCHITECTURES=arm64` when installing
- `pip install kp` with Intel Python instead

**Comment by axsaucedo** [comment]
Closing as fix was merged
