### ISSUE TITLE
Running Android app

### ISSUE THREAD

**Issue by DanMotataeanu** [KomputeProject/kompute#234]
Hey,

I've got the repo & tried to run android app on a pixel 2 and I get multiple errors when trying to build it, step would be
`app:externalNativeBuildArm8Debug`

Issues come from `memory`, `vector`, `Manager.cpp`, `vulkan.hpp`.
<details>
  <summary>memory</summary>

    In file included from D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\set:427:
    In file included from D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\__tree:15:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\memory:1514:22: error: type 'std::__ndk1::allocator_traits<unsigned int *>::allocator_type' (aka 'unsigned int *') cannot be used prior to '::' because it has no members
</details>

<details>
  <summary>vector</summary>

    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:331:22: note: in instantiation of template class 'std::__ndk1::allocator_traits<unsigned int *>' requested here
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:470:15: note: in instantiation of template class 'std::__ndk1::__vector_base<vk::PhysicalDevice, unsigned int *>' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:480:30: error: 'reference' is a protected member of 'std::__ndk1::__vector_base<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:334:54: note: declared protected here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:481:30: error: 'const_reference' is a protected member of 'std::__ndk1::__vector_base<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:335:54: note: declared protected here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:483:30: error: 'difference_type' is a protected member of 'std::__ndk1::__vector_base<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:336:54: note: declared protected here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:484:30: error: 'pointer' is a protected member of 'std::__ndk1::__vector_base<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:337:54: note: declared protected here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:485:30: error: 'const_pointer' is a protected member of 'std::__ndk1::__vector_base<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:338:54: note: declared protected here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:491:37: error: type 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::allocator_type' (aka 'unsigned int *') cannot be used prior to '::' because it has no members
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:507:11: error: type 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::__base' (aka '__vector_base<vk::PhysicalDevice, unsigned int *>') is not a direct or virtual base of 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:2020:39: error: no member named '__begin_' in 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:1083:38: error: no member named '__end_cap' in 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:2018:15: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::__append' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:833:17: error: call to non-static member function without an object argument
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:2020:15: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::__destruct_at_end' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:833:17: error: '__destruct_at_end' is a protected member of 'std::__ndk1::__vector_base<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:375:10: note: declared protected here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:698:47: error: no member named '__begin_' in 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:891:39: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::data' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:834:9: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::__annotate_shrink' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:2020:15: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::__destruct_at_end' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:659:25: error: call to non-static member function without an object argument
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:891:56: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::capacity' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:834:9: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::__annotate_shrink' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:2020:15: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::__destruct_at_end' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:659:25: error: 'capacity' is a protected member of 'std::__ndk1::__vector_base<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:371:15: note: declared protected here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:656:46: error: no member named '__end_' in 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:11:
    In file included from ..\..\..\..\..\..\..\..\external\fmt\include\fmt\core.h:18:
    D:\Tools\Android\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1\vector:1283:30: error: no member named '__alloc' in 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>'

</details>

<details>
  <summary>Manager.cpp</summary>

    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of template class 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of template class 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
    D:\git\vulkan-kompute\src\Manager.cpp:293:22: note: in instantiation of function template specialization 'vk::Instance::enumeratePhysicalDevices<unsigned int *, nullptr_t>' requested here
</details>

<details>
  <summary>vulkan.hpp</summary>

    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68106:38: error: member reference base type 'const nullptr_t' is not a structure or union
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68110:40: error: member reference base type 'const nullptr_t' is not a structure or union
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68101:43: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::vector' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68109:25: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::resize' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68109:25: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::resize' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68109:25: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::resize' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68109:25: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::resize' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68109:25: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::resize' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68115:65: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::size' requested here
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:56:30: note: expanded from macro 'VULKAN_HPP_ASSERT'
    In file included from D:\git\vulkan-kompute\src\Manager.cpp:7:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Manager.hpp:6:
    In file included from ..\..\..\..\..\..\..\..\src\include\kompute\Core.hpp:13:
    D:\Tools\Android\ndk\21.2.6472646\sources\third_party\vulkan\src\include\vulkan\vulkan.hpp:68118:12: note: in instantiation of member function 'std::__ndk1::vector<vk::PhysicalDevice, unsigned int *>::vector' requested here

</details>

Did you ever encounter this?

Thanks,
Dan

**Comment by axsaucedo** [comment]
I haven't gotten this, but could you try again? We have updated the core dependencies to drop a large number of dependencies which should make it easier to support across multiple platforms.

**Comment by axsaucedo** [comment]
Thank you for reporting this, I can confirm this is now resolved via https://github.com/KomputeProject/kompute/pull/266
