### ISSUE TITLE
Python "getting started" example fails

### ISSUE THREAD

**Issue by david-cortes** [KomputeProject/kompute#252]
The docs have a section "Getting started" for the python version:
https://kompute.cc

The example there however fails to execute: it calls `kp.Shader`, which throws an error:
```
AttributeError: module 'kp' has no attribute 'Shader'
```

Additionally, it does not import `kp` within the script, which has to be added manually.

The example from the readme (which is a bit different) IMO is not a good example as it requires cloning the repository.

**Comment by axsaucedo** [comment]
Thank you @david-cortes this is now fixed in https://github.com/KomputeProject/kompute/issues/248
