### ISSUE TITLE
Data-transfer for Integrated GPU

### ISSUE THREAD

**Issue by singam-sanjay** [KomputeProject/kompute#258]
I understand the necessity to move the data between local (RAM) and GPU memory for a discreet GPU like an NVIDIA or Radeon card.

Is it necessary to move data to GPU memory if the GPU is integrated (like Iris Graphics) or is part of the SoC (like Adreno) ?

**Comment by axsaucedo** [comment]
From my understanding you would still have to copy it at least to a vulkan buffer, which would require still a memcpy, having said that you would be able to copy to a host shared memory, which in this case could be the same memory. You may not need to copy it to the deviceOnly visible memory, although for optimal configuration it may require checking the nuances of your respective integrated graphics card.

**Comment by axsaucedo** [comment]
Closing as seems question resolved
