### ISSUE TITLE
Technically can Kompute be modified to support data visualization?

### ISSUE THREAD

**Issue by Biobots** [KomputeProject/kompute#260]
Since kompute is based on Vulkan, am I able to modify the `manager` class to pick and render a tensor on screen directly by mapping it to a texture and bypass the data synchronization between GPU and CPU?

**Comment by axsaucedo** [comment]
@Biobots your thinking is along the correct path - Kompute augments the computing capabilities of Vulkan, and works with a "Bring your own vulkan" approach, which means that if you have a graphical Vulkan application that is rendering graphics, you are able to leverage Kompute into that application to simplify any particular computations. Namely you are able to initialise a Manager with an existing Vulkan Application, Instance and Device. That means that any rendering would still be done by your graphical rendering logic, as opposed to Kompute. Hope that helps.

**Comment by Biobots** [comment]
> @Biobots your thinking is along the correct path - Kompute augments the computing capabilities of Vulkan, and works with a "Bring your own vulkan" approach, which means that if you have a graphical Vulkan application that is rendering graphics, you are able to leverage Kompute into that application to simplify any particular computations. Namely you are able to initialise a Manager with an existing Vulkan Application, Instance and Device. That means that any rendering would still be done by your graphical rendering logic, as opposed to Kompute. Hope that helps.

Thank you! I will try this later.
