### ISSUE TITLE
Error when enabling `KOMPUTE_ENABLE_SPDLOG`

### ISSUE THREAD

**Issue by david-cortes** [KomputeProject/kompute#268]
Using `#define KOMPUTE_ENABLE_SPDLOG` (as is suggested by the ifdef's in the examples) triggers a compilation error:
```
kompute/Kompute.hpp:640:26: error: #if with no expression
  640 | #if KOMPUTE_ENABLE_SPDLOG
```

This is regardles of whether `#include <spdlog/spdlog.h>` is added before or not.

**Comment by axsaucedo** [comment]
How are you building the project? By default a value is provided to KOMPUTE_ENABLE_SPDLOG by cmake, so it should still work, are you looking to disable it? If that's the case you just have to add KOMPUTE_ENABLE_SPDLOG=0 - could you try that?

**Comment by david-cortes** [comment]
Oh, I was thinking this was a configuration option for projects that link to this library rather than for the library itself.

**Comment by axsaucedo** [comment]
No worries @david-cortes - this is certainly an external variable for users to configure accordingly, but the main thing is that it has to be set to a value otherwise it would error out as you suggest - I think perhaps adding a further note in the docs could provide more context
