### ISSUE TITLE
Discord link in README and docs is broken

### ISSUE THREAD

**Issue by ScheissSchiesser** [KomputeProject/kompute#276]
The link to the discord is given by this line in the README:
https://github.com/KomputeProject/kompute/blame/master/README.md#L67

here is the link given in the above:
https://discord.gg/ywjaBH6v24

Discord tells me this link is broken.

I would really like to get up and running with Kompute, so being able to join the Discord would be super helpful. Thank you!

**Comment by axsaucedo** [comment]
Thank you very much for the heads up - I hadn't realised the discord link was broken, I have now created a new link which you can use https://discord.gg/MaH5Jv5zwv I will update it in the readme as well
