### ISSUE TITLE
memory sanitizer reports errors for simple example

### ISSUE THREAD

**Issue by mkandulavm** [KomputeProject/kompute#298]
Hi

I am trying to integrate the given simple multiplication example into a project. I use the memory sanitizer by default and it is showing following info.

single_include/kompute/Kompute.hpp:1049:30: runtime error: member call on address 0x555559947500 which does not point to an object of type 'TensorT'
0x555559947500: note: object has invalid vptr

Please help on how to proceed.

Also, in debug mode I am getting a segmentation fault in manager.cpp at this line
this->mInstance->destroyDebugReportCallbackEXT(

why is this happening ?

**Comment by mkandulavm** [comment]
Once I defined this , the problem got resolved 
KOMPUTE_OPT_DISABLE_VK_DEBUG_LAYERS

thank you.

**Comment by axsaucedo** [comment]
Nice - thank you for updating, it does seem like there is a raised warning from the debug layers so we'll have a look. Thank you for reporting

**Comment by feliwir** [comment]
I'm getting a crash for this line aswell:
```
[Jun 28 2023 13:36:45] [debug] [/home/stephan/Development/bcenc-gpu/build/_deps/kompute-src/src/Manager.cpp:26] [VALIDATION]: Validation - Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x12460c0, type = VK_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT; | MessageID = 0x5d6b67e2 | Couldn't find VkDebugReportCallbackEXT Object 0x12460c0. This should not happen and may indicate a bug in the application.
```

**Comment by axsaucedo** [comment]
@feliwir thank you for reporting this issue, however it seems it's a different issue, quite a strange one.

Could you please create a new issue with the details on your versions of vulkan, etc (as per the issue creation tempalte)?

We'll close this issue as several debug layer issues have been resolved since the most recent version.
