### ISSUE TITLE
Android sample is not compiling

### ISSUE THREAD

**Issue by mukovozov** [KomputeProject/kompute#305]
I'm really excited about your project, cause it may help us to overcome CPU restrictions, but, unfortunately, I'm not able to build the Android sample.

I'm getting an error message like this:
```
.../android-simple/app/src/main/cpp/CMakeLists.txt : C/C++ arm8Debug|arm64-v8a : CMake Error at 
...kompute/examples/android/android-simple/app/src/main/cpp/../../../../../../../src/CMakeLists.txt:73 (add_subdirectory):
  The source directory

.../kompute/external/Vulkan-Headers

  does not contain a CMakeLists.txt file.
```

I assume the problem is in this line: `add_subdirectory(../../../../../../../ ${CMAKE_CURRENT_BINARY_DIR}/kompute_build)`.  
I've tried to replace it with `includeDirectories(absolute path to kompute directory)`, but then I see many other compilation errors.  

I'm not very experienced in NDK and building C libraries in general, so maybe you could advise me something because I've seen that you have tested the Android sample recently and it worked for you.

**Comment by axsaucedo** [comment]
@mukovozov you will need to make sure to initialise all the git submodules, you can do so through `git submodule update --init --recursive`

**Comment by mukovozov** [comment]
thanks for a quick reply!  
Yeah, I did it manually before, but now I can see other issues as: 
```
kompute/VERSION:1:1: error: expected unqualified-id
```  
```
sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
```   
and more.   
I use the NDK version that is defined in build.gradle file.

**Comment by axsaucedo** [comment]
Ok I see, another thing that I can think about looking at the issue, it may be potentially a couple of things to consider. Indeed as you suggested the first most important things are to ensrue that the version of NDK is the correct one, as well as the version of the android development setup. Further to that it may be worth ensuing that the vulkan headers / packages are of the correct version.

**Comment by axsaucedo** [comment]
Having said that, I'm not sure why the VERSION file is appearing as an error, that should not really be a file that would be compiled / processed

**Comment by mukovozov** [comment]
Oh, I've launched the app! I've changed type from `auto` to `std::string` and removed `value` from `vk::Pipeline pipeline =
      this->mDevice->createComputePipeline(*this->mPipelineCache, pipelineInfo).value;`

**Comment by mukovozov** [comment]
I'm closing the issue due to I've managed to build the app and the errors were probably specific and there is no need to fix anything from your side. Thanks for the response anyway!
