### ISSUE TITLE
Parser failure with Vulkan SDK 1.3.236

### ISSUE THREAD

**Issue by silkskier** [KomputeProject/kompute#317]
Tested on Ubuntu (Asus FX505DY with Ryzen 3550H and Radeon RX 560X).

Trying to run 'cmake ..' results in "No valid Vulkan API version found in vulkaninfo.  Does your GPU (driver)
  support Vulkan?" error.
  
  With cmake .. version -DKOMPUTE_OPT_DISABLE_VULKAN_VERSION_CHECK=O everything works just fine.
  
  It looks like Kompute is trying to use header version 1.2.231 despite finding version 1.3.231:
  
  '--   KOMPUTE_OPT_USE_BUILT_IN_VULKAN_HEADER: ON
--   KOMPUTE_OPT_BUILT_IN_VULKAN_HEADER_TAG: v1.3.231
-- =======================================================
-- Ensuring the currently installed driver supports the Vulkan version requested by the Vulkan Header.
-- Found Vulkan Header version: 1.2.231'.

Here is my 'cmake ..' and 'vulkaninfo' output:
[cmake_output.txt](https://github.com/KomputeProject/kompute/files/10462780/cmake_output.txt)
[vulkainfo_output (1).txt](https://github.com/KomputeProject/kompute/files/10462782/vulkainfo_output.1.txt)

**Comment by axsaucedo** [comment]
I can confirm working with 1.3.275
