### ISSUE TITLE
windows building error

### ISSUE THREAD

**Issue by 0106WeiWeiDeng** [KomputeProject/kompute#318]
hi,

I build kcompute 0.8.1 using cmake(GUI), but an error occurred, the following is the ouput :

The C compiler identification is MSVC 19.34.31937.0
The CXX compiler identification is MSVC 19.34.31937.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Found Vulkan: D:/vulkan_sdk/Lib/vulkan-1.lib (found version "1.3.236") found components: glslc glslangValidator 
CMake Error at src/CMakeLists.txt:87 (find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.

Configuring incomplete, errors occurred!

**Comment by 0106WeiWeiDeng** [comment]
After installing fmtlib, and setting "fmt_DIR" , cmake configures with no error, but, there were some building errors: 
1) kompute-0.8.1\src\Algorithm.cpp(307,27): error C2440: Cannot convert vk::ResultValue<vk::Pipeline> to vk::Pipeline
2) fmt/core.h(1728,7): error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt'

**Comment by arashandishgar** [comment]
Hi ,
 it seems this #201 address your problem

**Comment by 0106WeiWeiDeng** [comment]
Thanks, I download the code of master branch (not 0.8.1), and configure it with default cmake options, build successfully:

1) download the zip file of the master branch, unzip it, and open PowerShell in kompute-master diretory
2) mkdir build 
3) cmake ..
4) cmake --build . --config Release --clean-first
5) cmake --install .  # errors occur after runing this command, but removing some cmake code(two install files not exist), it run successfully

at last, build/install diretory contains the installed files.
