### ISSUE TITLE
windows building error

### ISSUE THREAD

**Issue by fzStella** [KomputeProject/kompute#321]
I build kcompute 0.8.1 using cmake(GUI) on Windows, but an error occurred.
Steps to reproduce

      $ git clone --branch v0.8.1 --recursive https://github.com/KomputeProject/kompute
      $ cd kompute/examples/array_multiplication/
      $ cmake -Bbuild/ -DCMAKE_BUILD_TYPE=Debug -DKOMPUTE_OPT_INSTALL=0 -DKOMPUTE_OPT_REPO_SUBMODULE_BUILD=1 -DKOMPUTE_OPT_ENABLE_SPDLOG=1

Until now, there's no problem(maybe).
Then I open Visual studio 2017, and open komute_ array_ mult.sln, try to run Main.cpp, then get some error.It tell me it can't find the file "ALL_ BUILD" in the "C:\kompute\examples\array_multiplication\build" 
I don't know what steps are missing or what steps are wrong
(Solution configuration is "release Win32")

**Comment by ToKiNoBug** [comment]
This is a bug caused by cmake and VS. `ALL_BUILD` is a "virtual" target to build all targets, it't not runnable. You need to select another target in VS.

**Comment by ToKiNoBug** [comment]
I think this issue can be closed because it has nothing to do with kompute. You can draw an issue to cmake, or report it as a bug to VS, or simply select another target, or use another generator like ninja.
