### ISSUE TITLE
After compilation, only the library file has no header file

### ISSUE THREAD

**Issue by ZhangXiChang** [KomputeProject/kompute#324]
execute:
cmake -Bbuild -G "MinGW Makefiles" -DKOMPUTE_OPT_DISABLE_VULKAN_VERSION_CHECK=ON -DKOMPUTE_OPT_BUILD_AS_SHARED_LIB=OFF
cd build
mingw32-make.exe -j14

result:
There are library files, but no header files. Execute 'mingw32 make. exe install' prompt:
CMake Error at src/cmake_install.cmake:45 (file):
  file INSTALL cannot find
  "C:/Project/GCC/AI/pack/kompute/build/kompute/komputeConfigVersion.cmake":
  File exists.
Call Stack (most recent call first):
  cmake_install.cmake:52 (include)

mingw32-make: *** [Makefile:99: install] Error 1

**Comment by axsaucedo** [comment]
@ZhangXiChang what are you building atm? Is it one of the examples or your own project? If you can provide more details this can be explored further - for completeness the headers are in the include folder

**Comment by evanokeeffe** [comment]
Having a similar issue on Ubuntu 22.04 with install to /usr/local/lib
during make install getting this 

`
CMake Error at src/cmake_install.cmake:50 (file):
  file INSTALL cannot find
  "/home/user/Libraries/kompute/build/kompute/komputeConfigVersion.cmake":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:57 (include)
`

just using basic options for building 
cd kompute 
mkdir build && cd build
cmake ..
make -j4
sudo make install

**Comment by ToKiNoBug** [comment]
I have met same issue too on windows with MSVC and clang, and on archlinux with gcc and clang. There's some thing wrong with its cmake script, I will try to fix it.
