### ISSUE TITLE
Release cadence

### ISSUE THREAD

**Issue by samuel-emrys** [KomputeProject/kompute#333]
Hi Team,

I'm currently putting together a [conan package](https://docs.conan.io/2/introduction.html) for kompute, and I've noticed that the latest release, v0.8.1, is reasonably old and the CMakeLists.txt has advanced substantially since this release. The improvements you've made here make it easier to package, so I'd rather pull these in if possible. The easiest way for me to do that would be if you cut a new release with these changes.

There are other ways I can do this:
* Take a snapshot of the repo as a date (less desirable, sometimes issues associated with version comparisons later on)
* Create a local patch for 0.8.1 to either advance the build system in isolation
* Create a local patch to inject the necessary `find_package` statements to inject dependencies from conan

These all present additional maintenance challenges. However, noting that there are other options available, are you able to advise what your plans are for a future release?

For tracking, this relates to https://github.com/conan-io/conan-center-index/issues/10975

**Comment by samuel-emrys** [comment]
@axsaucedo are you able to advise what intentions you have for future releases? Can I expect one any time soon?

**Comment by axsaucedo** [comment]
Thank you for following up @samuel-emrys, we will be doing a release this month for the latest master build - we had explored automated releases but it's something we parked, but could be explored this year again.

**Comment by axsaucedo** [comment]
Closing following recent release
