### ISSUE TITLE
Issues with compiling python module ubuntu 22.04

### ISSUE THREAD

**Issue by evanokeeffe** [KomputeProject/kompute#342]
Hey all, great library , using this is saving some amount of time on boiler code for our projects.
I noticed there was some issues with compiling the project python module, thought I'd mention the fixes I've found.

In Logger.hpp there was some issues with the if statements when using logging with python and fmt, mainly redefinition of KP_DEBUG. In the build system using the standard install for ubuntu apt install libfmt8 libfmt-dev , this only installs a static library so FPIC needs to be added using the internal FMT package for build, this is needed for libfmt,kp_logger and then the python module .

doing this I know have python module built and with logging for Ubuntu 22.04

I'll send in a pull request with the needed changes for building the python modules

**Comment by axsaucedo** [comment]
Great to hear you have found the library useful - sounds good, let us know if any questions

**Comment by axsaucedo** [comment]
Closing this, reopening when revisiting
