### ISSUE TITLE
State of the Project

### ISSUE THREAD

**Issue by lukas-the-wizard** [KomputeProject/kompute#344]
Is it maintained? Should software be build or depending on this?

llama.cpp potentially using this project 
https://github.com/ggerganov/llama.cpp/pull/4456

this project already using it
https://github.com/nomic-ai/gpt4all

**Comment by tikikun** [comment]
I think this project is very potential given nomic ai implementation using Vulkan + Kompute giving very good result

**Comment by axsaucedo** [comment]
Great find - exciting to see that GPU4all is using Kompute! The project is stil maintained as part of the Linux Foundation

**Comment by axsaucedo** [comment]
We have opened https://github.com/nomic-ai/gpt4all/issues/1852 support contributions across the GPT4All project as well as upstream contributions to bring some of these extensions
