### ISSUE TITLE
Integrate ZLUDA for AMD CUDA

### ISSUE THREAD

**Issue by GermanAizek** [KomputeProject/kompute#358]
@axsaucedo, hi

**Describe the feature**
https://github.com/vosen/ZLUDA
it can give feature run CUDA program on amd gpus and speed up work on amd if cuda code is optimized vs opencl.

**Comment by amitbar05** [comment]
Wasting time on an almost dead on arrival (not funded anymore) project, instead of improving the Vulkan backend, which is supported on all modern GPUs.
Yea... no thanks.
