### ISSUE TITLE
CMake build bug when installing with KOMPUTE_OPT_USE_BUILT_IN_FMT off

### ISSUE THREAD

**Issue by SimLeek** [KomputeProject/kompute#359]
Easy to work around. I just have to do this:
```
find_package(fmt REQUIRED)
find_package(kompute REQUIRED)
```
instead of:
```
find_package(kompute REQUIRED)
```
System: Arch Linux

Could be confusing if you don't know the workaround. Since it gives an error in the kompute cmake files:
```
[cmake] CMake Error at /usr/local/lib/cmake/kompute/komputeTargets.cmake:69 (set_target_properties):
[cmake]   The link interface of target "kompute::kp_logger" contains:
[cmake] 
[cmake]     fmt::fmt
```

**Comment by kwsp** [comment]
Are you using the latest version of Kompute? This issue should be fixed already: https://github.com/KomputeProject/kompute/blob/40f9adf62e270d679ce5c9a72b0fae01155a094d/CMakeLists.txt#L191

**Comment by axsaucedo** [comment]
+1 this was indeed an issue but was resolved
