### ISSUE TITLE
Texture support?

### ISSUE THREAD

**Issue by mitjap** [KomputeProject/kompute#361]
Our projects often use textures for data storage and access.

I've been looking over examples, source and documentation but I don't see any mention of texture support. Is it implemented? What is the current status of this?

**Comment by axsaucedo** [comment]
Hello @mitjap - at the moment we only support the compute pipeline, and hence the primary elements would be buffers - there's no current plans on supporting other types of (graphics) pipelines in vulkan at the moment

**Comment by mitjap** [comment]
I often use textures as data storage for compute pipeline. Textures provider better 2D data locality using [Z-order curve](https://en.m.wikipedia.org/wiki/Z-order_curve). Data interpolation is also often useful for our kind of algorithms.

It would be a great addition to this library.

**Comment by robquill** [comment]
@mitjap , https://github.com/KomputeProject/kompute/pull/388 hopefully adds what you wanted :)
