### ISSUE TITLE
C FFI for other language bindings

### ISSUE THREAD

**Issue by crystalthoughts** [KomputeProject/kompute#375]
Hi, are there any plans to offer a C wrapper so that other languages are more easily used with this framework?
Thanks!

**Comment by axsaucedo** [comment]
We are not planning a C-interface at the moment. The Python interface works as using C++ bindings it's possible to align object oriented design - exposing a purely functional interface would remove quite a lot of the functionality and design so not sure the effort would be worth. Probably using something like SWIG would be better, there was an implementation a while back creating an interface for golang: https://github.com/0x0f0f0f/kompute-go/tree/master. Certainly other language support that is maintained would be highly appreciated tho!
